# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:46658"
moniker = "node6"
fast_sync = true
db_backend = "leveldb"
log_level = "state:info,*:error"

[rpc]
laddr = "tcp://0.0.0.0:46657"

[p2p]
laddr = "tcp://0.0.0.0:46656"
seeds = "10.0.1.20:46656,10.0.1.21:46656,10.0.1.22:46656,10.0.1.23:46656,10.0.1.24:46656,10.0.1.25:46656"
